version: "3"
services:
  web:
    build:
      context: .
    ports:
      - 8080:80
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'blackcart'
      MYSQL_USER: 'blackcart'
      MYSQL_PASSWORD: 'blackcart'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:rw

